[2024-10-01T16:16:36.559+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sitemap_processing_pipeline.compare_and_trigger manual__2024-10-01T16:11:12.089647+00:00 [queued]>
[2024-10-01T16:16:36.624+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sitemap_processing_pipeline.compare_and_trigger manual__2024-10-01T16:11:12.089647+00:00 [queued]>
[2024-10-01T16:16:36.627+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-10-01T16:16:36.694+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): compare_and_trigger> on 2024-10-01 16:11:12.089647+00:00
[2024-10-01T16:16:36.946+0000] {standard_task_runner.py:57} INFO - Started process 84 to run task
[2024-10-01T16:16:36.972+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'sitemap_processing_pipeline', 'compare_and_trigger', 'manual__2024-10-01T16:11:12.089647+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/data_fetching_huber_dag.py', '--cfg-path', '/tmp/tmpqr6ych95']
[2024-10-01T16:16:36.976+0000] {standard_task_runner.py:85} INFO - Job 72: Subtask compare_and_trigger
[2024-10-01T16:16:37.482+0000] {task_command.py:415} INFO - Running <TaskInstance: sitemap_processing_pipeline.compare_and_trigger manual__2024-10-01T16:11:12.089647+00:00 [running]> on host f6937622df26
[2024-10-01T16:16:39.490+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sitemap_processing_pipeline' AIRFLOW_CTX_TASK_ID='compare_and_trigger' AIRFLOW_CTX_EXECUTION_DATE='2024-10-01T16:11:12.089647+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-01T16:11:12.089647+00:00'
[2024-10-01T16:16:41.141+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_fetching_huber_dag.py", line 144, in compare_versions_and_create_trigger
    raise ValueError(f"bucket_name ({bucket_name}) or s3_key ({s3_key}) not set")
ValueError: bucket_name (None) or s3_key (None) not set
[2024-10-01T16:16:41.327+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=sitemap_processing_pipeline, task_id=compare_and_trigger, execution_date=20241001T161112, start_date=20241001T161636, end_date=20241001T161641
[2024-10-01T16:16:41.576+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 72 for task compare_and_trigger (bucket_name (None) or s3_key (None) not set; 84)
[2024-10-01T16:16:42.166+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-01T16:16:42.389+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
