[2024-10-01T16:39:01.704+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: third_task_test.compare_and_trigger manual__2024-10-01T16:34:22.130372+00:00 [queued]>
[2024-10-01T16:39:01.718+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: third_task_test.compare_and_trigger manual__2024-10-01T16:34:22.130372+00:00 [queued]>
[2024-10-01T16:39:01.719+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 3
[2024-10-01T16:39:01.739+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): compare_and_trigger> on 2024-10-01 16:34:22.130372+00:00
[2024-10-01T16:39:01.752+0000] {standard_task_runner.py:57} INFO - Started process 79 to run task
[2024-10-01T16:39:01.759+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'third_task_test', 'compare_and_trigger', 'manual__2024-10-01T16:34:22.130372+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/data_fetching_huber_dag.py', '--cfg-path', '/tmp/tmpjcc_mlx4']
[2024-10-01T16:39:01.765+0000] {standard_task_runner.py:85} INFO - Job 92: Subtask compare_and_trigger
[2024-10-01T16:39:01.892+0000] {task_command.py:415} INFO - Running <TaskInstance: third_task_test.compare_and_trigger manual__2024-10-01T16:34:22.130372+00:00 [running]> on host f6937622df26
[2024-10-01T16:39:02.071+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='third_task_test' AIRFLOW_CTX_TASK_ID='compare_and_trigger' AIRFLOW_CTX_EXECUTION_DATE='2024-10-01T16:34:22.130372+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-01T16:34:22.130372+00:00'
[2024-10-01T16:39:02.084+0000] {logging_mixin.py:151} INFO - Attempting to read from bucket: huber-chatbot-project, key: sitemap_data/sitemap_data_2024.json
[2024-10-01T16:39:02.104+0000] {base.py:73} INFO - Using connection ID 'aws_default' for task execution.
[2024-10-01T16:39:02.107+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2024-10-01T16:39:05.541+0000] {logging_mixin.py:151} INFO - All versions:
[2024-10-01T16:39:05.542+0000] {logging_mixin.py:151} INFO - Version ID: Ia10oW2qleAaUSqHOu70VCE9NF4iAvLR, Last Modified: 2024-10-01 16:22:04+00:00
[2024-10-01T16:39:05.543+0000] {logging_mixin.py:151} INFO - Version ID: VJZAB4e.cfvlUirPV.j_sjD379KsjLgb, Last Modified: 2024-10-01 16:16:53+00:00
[2024-10-01T16:39:05.543+0000] {logging_mixin.py:151} INFO - Version ID: 4_.OUcqGu6kzbHujgrkoapppPVhxQ1rb, Last Modified: 2024-10-01 16:11:22+00:00
[2024-10-01T16:39:05.544+0000] {logging_mixin.py:151} INFO - Version ID: fx5Ts7q2jGGqgGb8RialAmpEXSQmRdka, Last Modified: 2024-10-01 16:10:17+00:00
[2024-10-01T16:39:05.544+0000] {logging_mixin.py:151} INFO - Version ID: vHNy3rFHDo1k2V0Djf4F78Vtrd9Xz70X, Last Modified: 2024-10-01 15:35:15+00:00
[2024-10-01T16:39:05.545+0000] {logging_mixin.py:151} INFO - Version ID: x0bn3Guv0yrPU3Qt1gFQEbM2Y1vDlMZ0, Last Modified: 2024-10-01 11:49:37+00:00
[2024-10-01T16:39:05.545+0000] {logging_mixin.py:151} INFO - Version ID: VbD9hb167blBUYfW.xlpYer9gMkMAWFm, Last Modified: 2024-10-01 11:39:07+00:00
[2024-10-01T16:39:05.546+0000] {logging_mixin.py:151} INFO - Version ID: hhDZnDI6ONOOK9ANT2reoJIVSf1.JBrP, Last Modified: 2024-10-01 11:26:22+00:00
[2024-10-01T16:39:05.546+0000] {logging_mixin.py:151} INFO - Version ID: Dio0QYWGkkzJwNKGeDCEb.uAgvpNgn5j, Last Modified: 2024-10-01 10:52:53+00:00
[2024-10-01T16:39:05.547+0000] {logging_mixin.py:151} INFO - Version ID: GK5yRFpxf5QlOspV_9rWAfvqRki4iHE., Last Modified: 2024-10-01 10:40:19+00:00
[2024-10-01T16:39:05.548+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_fetching_huber_dag.py", line 85, in compare_versions_and_create_trigger
    latest_content = s3_hook.read_key(key=S3_KEY, bucket_name=BUCKET_NAME, version_id=latest_version['VersionId'])
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 123, in wrapper
    bound_args = function_signature.bind(*args, **kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 3037, in bind
    return self._bind(args, kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 3026, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'version_id'
[2024-10-01T16:39:05.566+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=third_task_test, task_id=compare_and_trigger, execution_date=20241001T163422, start_date=20241001T163901, end_date=20241001T163905
[2024-10-01T16:39:05.597+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 92 for task compare_and_trigger (got an unexpected keyword argument 'version_id'; 79)
[2024-10-01T16:39:05.628+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-01T16:39:05.669+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
